### ISSUE TITLE
Problems with Robotics CS Nodeset

### ISSUE THREAD

**Issue by andre-fm** [OPCFoundation/UA-Nodeset#43]
Hello,

I am experiencing some problems when trying to import the "Opc.Ua.Robotics.NodeSet2.xml" and "Opc.Ua.Di.NodeSet2.xml" to UA Modeler software from Unified Automation.
With "modeling only" purpose, when importing the two .xml files I get this kind of errors "TypeDefinition not found (<number>)".
![example1](https://user-images.githubusercontent.com/781721/65613990-c7267280-dfae-11e9-8751-7400c7c09221.png)
![example2](https://user-images.githubusercontent.com/781721/65613991-c7267280-dfae-11e9-9ba3-982d7e0e95d6.png)
Is there anyone with the same kind of problem?

Best Regards,
André Martins

**Comment by xenonforlife** [comment]
Hi,
The Robotics CS makes use of some Type definitions from Amendment 1 and Amendment 11. However these (new) type definitions from the Ammendments have not yet been incorporated in the NodeSet files of the core standard. Therefore it results in such errors. 
These errors will all be taken care of with a new version of UaModeler which is soon to be released (as far as I know), since it would come with the updated core NodeSet files.
I hope this answers your query :)

Thanks,
Sup

**Comment by andre-fm** [comment]
Thanks for your comment . Then I will have to wait for the new version of UaModeler. :)

Regards,
André Martins

**Comment by Ayyubshaikh** [comment]
I am Also not able to add robotics nodeset file to UAModeler Models. Is it possible now to do it???

**Comment by GoetzGoerisch** [comment]
@Ayyubshaikh what errors do you see? I'm using this nodeset without issues in the UaModeler. But a new version is in the works to fix some other errors.

**Comment by Ayyubshaikh** [comment]
@GoetzGoerisch . I was doing it wrong. I figured it out. 
Does it look fine.
Thankyou
![16254207540854927704237907810840](https://user-images.githubusercontent.com/23493931/124394618-7c4b9a00-dd00-11eb-8ee9-59185887074a.jpg)
